version: '2'

services:
  lb:
    image: dockercloud/haproxy
    links:
      - shop1
      - shop2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"

  shop1:
    build: .
    hostname: shop1
    ports:
      - "8081"
  
  shop2:
    build: .
    hostname: shop2
    ports:
      - "8082"
  
  redis:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"